### ISSUE TITLE
redirect URLs with valid session strings that don't end in '=' to same URL with '=' suffix

### ISSUE THREAD

**Issue by strazto** [elisescu/tty-server#15]
Eg: 

![image](https://user-images.githubusercontent.com/39424834/94116443-687c2900-fe8e-11ea-80d6-543763f89526.png)

```bash
tty-share -useTLS=false -server localhost:6543

#>  Web terminal: http://localhost:5000/s/cQ8r2oQDIucjDy26ev2ROnPd8EthsEltlBgUy7AYje0=
```

clicking on the URL given in my terminal emulator doesn't include the suffixed `=` sign. 

Since this is a valid part of every URL (I think the 0 might also be?) would it be reasonable to redirect the following:

`https://go.tty-share.com/s/`*<session_id>*

to:

`https://go.tty-share.com/s/`*<session_id>*`=` 

?

**Comment by elisescu** [comment]
Good point. I had in mind to fix that, but not by a redirection, and instead by a manual encoding function that doesn't include these symbols, so the final session ID is still secure enough, but also URL friendly.

I am in the middle of some refactoring, as I want to add support for sharing the terminal in the local network, without using a public server, and I'll keep this in mind :)

**Comment by elisescu** [comment]
This has been fixed in the replacement project, and the URL looks a bit more different now (also longer).
