### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by djmattyg007** [elisescu/tty-server#3]
It would make packaging a lot easier :)

**Comment by elisescu** [comment]
Hey @djmattyg007 ! I finally manage to get back to you :).

I have decided to change the architecture of how this works, and deprecated the tty-server, replacing it with tty-proxy. I added here a few words on why: https://github.com/elisescu/tty-share/blob/master/doc/old-version.md

The tty-proxy is now tagged, so feel free to use that one instead.
