### ISSUE TITLE
Using docker install instructions, web interface gives ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by strazto** [elisescu/tty-server#8]
I'm trying to setup a dev env so I can make a relatively small PR (I'll raise an issue for that later), & getting this far works:

```bash
#!/usr/bin/env bash

docker run \
  -p 6543:6543 -p 5000:5000 \
  -e URL=http://localhost:5000 \
  --cap-drop=all --rm \
  tty-server
```

```bash
 tty-share -useTLS=false -server localhost:6543
Web terminal: http://localhost:5000/s/iVTfcMl4A628ZMD-YT9I2lkfkDrwQEl7y0164GDfpo8=
```

However, at the web terminal I consistently get connection reset.

**Comment by strazto** [comment]
Idk why this was, but I just used vagrant. 
If anyone can comment, I appreciate it.

(ETA that it might just be an issue with my own docker installation, or how docker interacts with my firewall, rather than the dockerfile)

**Comment by elisescu** [comment]
Hey, @matthewstrasiotto! Did you figure it out? It's weird it does that, but it doesn't really sound like it's a problem on the tty-server, no? I guess you don't get into the same issue if you just run it on the host (so no docker involved at all)?
Also, what does the dev console say? Does the websocket connection get simply cut? What do the tty-server logs say?

**Comment by elisescu** [comment]
Closing this issue now. The tty-server has been replaced by tty-proxy, moving the "web" part into the tty-share command itself.
